version: "3.8"

volumes:
  saga-wx-sqlite3-db:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: saga-wx
    container_name: saga-wx
    tty: true
    ports:
      - "8501:8501"
    working_dir: /app
    volumes:
      - ./:/app
      - saga-wx-sqlite3-db:/var/lib/sqlite3
    environment:
      - DISPLAY=$DISPLAY
      - TZ=Asia/Tokyo
    network_mode: "bridge"
